- name: "Set default '_mvn_cmdline_args'."
  set_fact:
    _mvn_cmdline_args: "{{ conga_aem_packages_maven_opts }}"

- name: "Set vault force define for '{{ item.path | basename }}' to {{ item.force }} in _mvn_cmdline_args"
  set_fact:
    _mvn_cmdline_args: "{{ _mvn_cmdline_args }} -Dvault.force={{ item.force }}"
  when: item.force is defined

- name: "Set vault httpSocketTimeoutSec define for '{{ item.path | basename }}' to {{ item.httpSocketTimeoutSec }}"
  set_fact:
    _mvn_cmdline_args: "{{ _mvn_cmdline_args }} -Dvault.httpSocketTimeoutSec={{ item.httpSocketTimeoutSec }}"
  when: item.httpSocketTimeoutSec is defined

- name: Add custom Maven settings to _mvn_cmdline_args.
  set_fact:
    _mvn_cmdline_args: "{{ _mvn_cmdline_args }} --settings={{ conga_aem_packages_maven_settings }}"
  when: conga_aem_packages_maven_settings is defined

- name: Add command line arguments for logging to file.
  set_fact:
    _mvn_cmdline_args: "{{ _mvn_cmdline_args }} | tee -a {{ conga_aem_packages_maven_logfile }}"
  when: conga_aem_packages_maven_logging

- name: "Set environment specific wcmio-content-package-maven-plugin version"
  set_fact:
    _content_package_maven_plugin_version:
      "{{ conga_version_info['io.wcm.maven.plugins:wcmio-content-package-maven-plugin']
      | default(conga_aem_packages_wcmio_content_package_maven_plugin_version) }}"
  changed_when:
    _content_package_maven_plugin_version != conga_aem_packages_wcmio_content_package_maven_plugin_version

- name: "Use interactive mode for '{{ item.path | basename }}'"
  pause:
    prompt: "Continue with deploying {{ item.path | basename }}?"
  when:
    - conga_aem_packages_interactive_packages is defined
    - (item.path | basename) in conga_aem_packages_interactive_packages

- name: "Deploy AEM package: {{ item.path | basename }}"
  shell: >
    {{ conga_aem_packages_maven_cmd }}
    io.wcm.maven.plugins:wcmio-content-package-maven-plugin:{{ _content_package_maven_plugin_version }}:install
    -Dvault.serviceURL={{ conga_aem_packages_service_url }}
    -Dvault.file={{ item.path }}
    -Dvault.userId={{ conga_aem_packages_user }}
    -Dvault.password='{{ conga_aem_packages_password }}'
    -Dvault.delayAfterInstallSec={{ item.delayAfterInstallSec | default('0') }}
    -Dvault.recursive={{ item.recursive | default('true') }}
    {{ _mvn_cmdline_args }}
  args:
    chdir: "{{ conga_config_path }}"
  delegate_to: "{{ conga_aem_packages_maven_host }}"
  become: false
  register: _mvn_result
  changed_when:
    - _mvn_result.stdout is defined
    - conga_aem_packages_wcmio_content_package_maven_plugin_changed_output in _mvn_result.stdout
  tags:
    - skip_ansible_lint

- name: Fail if Maven stdout is undefined or Maven build has failed.
  fail:
    msg: "{{ _mvn_result }}"
  when: _mvn_result.stdout is not defined or _mvn_result.stdout.find('BUILD FAILURE') != -1

  # Restart if the package has actually been installed and it has been declared as necessary and
  # allow overriding the requiresRestart property from the package metadata in the CONGA configuration
- name: Restart AEM if required by package metadata.
  command: /bin/true
  notify: restart aem
  when: (conga_aem_packages_wcmio_content_package_maven_plugin_changed_output in _mvn_result.stdout) and
        (item.requiresRestart |
         default(item.aemContentPackageProperties.requiresRestart is defined and
         item.aemContentPackageProperties.requiresRestart | bool))

- name: Flush pending (restart) handlers before installation of next package.
  meta: flush_handlers
