- name: "Set default vault force define for '{{ item.path | basename }}'"
  set_fact:
    _item_vault_force_define: ""

- name: "Set vault force define for '{{ item.path | basename }}' to {{ item.force }}"
  set_fact:
    _item_vault_force_define: "-Dvault.force={{ item.force }}"
  when: item.force is defined

- pause:
    prompt: "Continue Deploying AEM package: {{ item.path | basename }}?"

- name: "Deploy AEM package: {{ item.path | basename }}"
  shell: >
    {{ conga_aem_packages_maven_cmd }}
    io.wcm.maven.plugins:wcmio-content-package-maven-plugin:{{ conga_aem_packages_plugin_version }}:install
    -Dvault.serviceURL={{ conga_aem_packages_service_url }}
    -Dvault.file={{ item.path }}
    -Dvault.userId={{ conga_aem_packages_user }}
    -Dvault.password={{ conga_aem_packages_password }}
    -Dvault.delayAfterInstallSec={{ item.delayAfterInstallSec | default('0') }}
    {{ _item_vault_force_define }}
    -Dvault.recursive={{ item.recursive | default('true') }}
  args:
    chdir: "{{ conga_config_path }}"
  delegate_to: "{{ conga_aem_packages_maven_host }}"
  become: false
  register: _mvn_result
  changed_when: _mvn_result.stdout is defined and conga_aem_packages_changed_output in _mvn_result.stdout
  #failed_when: "'BUILD FAILURE' in _mvn_result.stderr"

- name: Fail if Maven stdout is undefined.
  fail:
    msg: "{{ _mvn_result }}"
  when: _mvn_result.stdout is undefined

- name: "Wait for installer bundle '{{ item.installerBundle }}' to be uninstalled (installation complete)"
  uri:
    url: "{{ conga_aem_bundle_status_url }}"
    return_content: yes
    force_basic_auth: yes
    user: "{{ conga_aem_packages_user }}"
    password: "{{ conga_aem_packages_password }}"
    status_code: -1,200
  register: result
  until:
    - result.content != ""
    - result.content.find(item.installerBundle) == -1
  retries: "{{ conga_aem_bundle_status_timeout // conga_aem_bundle_status_retry_delay }}"
  delay: "{{ conga_aem_bundle_status_retry_delay }}"
  when:
    - item.installerBundle is defined
    - item.installerBundle != ""
    - conga_aem_packages_changed_output in _mvn_result.stdout

  # Restart if the package has actually been installed and it has been declared as necessary and
  # allow overriding the requiresRestart property from the package metadata in the CONGA configuration
- name: Restart AEM if required by package metadata.
  command: /bin/true
  notify: restart aem
  when: (conga_aem_packages_changed_output in _mvn_result.stdout) and
        (item.requiresRestart |
         default(item.aemContentPackageProperties.requiresRestart is defined and
         item.aemContentPackageProperties.requiresRestart | bool))

- name: Flush pending (restart) handlers before installation of next package.
  meta: flush_handlers
